---
abstract: 'JSON view for your data'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-JSON
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.6
  JSON::Any: 1.15
  MRO::Compat: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.25
