---
abstract: 'JSON view for your data'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-JSON
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.6
  JSON::Any: 1.15
  MRO::Compat: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/catalyst-view-json.git
version: 0.32
