abstract: JSON view for your data
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  JSON: 0
  JSON::Converter: 0
  JSON::Parser: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-View-JSON
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.6
  JSON::Any: 0
version: 0.17
