---
abstract: 'JSON view for your data'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-JSON
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.6
  JSON::MaybeXS: '1.003000'
  MRO::Compat: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perl-catalyst/Catalyst-View-JSON.git
version: '0.35'
